ext_uri_sources = files(
    'php_uri.c',
    'php_uri_common.c',
    'uri_parser_php_parse_url.c',
    'uri_parser_rfc3986.c',
    'uri_parser_whatwg.c',
    'uriparser/src/UriCommon.c',
    'uriparser/src/UriCompare.c',
    'uriparser/src/UriCopy.c',
    'uriparser/src/UriEscape.c',
    'uriparser/src/UriFile.c',
    'uriparser/src/UriIp4.c',
    'uriparser/src/UriIp4Base.c',
    'uriparser/src/UriMemory.c',
    'uriparser/src/UriNormalize.c',
    'uriparser/src/UriNormalizeBase.c',
    'uriparser/src/UriParse.c',
    'uriparser/src/UriParseBase.c',
    'uriparser/src/UriQuery.c',
    'uriparser/src/UriRecompose.c',
    'uriparser/src/UriResolve.c',
    'uriparser/src/UriSetFragment.c',
    'uriparser/src/UriSetHostAuto.c',
    'uriparser/src/UriSetHostCommon.c',
    'uriparser/src/UriSetHostIp4.c',
    'uriparser/src/UriSetHostIp6.c',
    'uriparser/src/UriSetHostIpFuture.c',
    'uriparser/src/UriSetHostRegName.c',
    'uriparser/src/UriSetPath.c',
    'uriparser/src/UriSetPort.c',
    'uriparser/src/UriSetQuery.c',
    'uriparser/src/UriSetScheme.c',
    'uriparser/src/UriSetUserInfo.c',
    'uriparser/src/UriShorten.c',
    'uriparser/src/UriVersion.c',
)

shared_module(
    'uri',
    [ext_uri_sources],
    name_prefix: '',
    c_args : [],
    # annoyingly, doesn't work: we still need to put ext/uri/uriparser/include in the root includes
    include_directories : [includes, 'uriparser/include',],
    dependencies: [],
    install : true,
)
