project(
    'punk',
    'c', 'cpp',
    meson_version : '>= 1.3.0',
    version : '0.1',
    default_options : ['warning_level=0', 'c_std=gnu23'],
)

cflags = [
]

cc = meson.get_compiler('c')
add_project_arguments(cc.get_supported_arguments(cflags), language: 'c')
add_project_arguments('-DHAVE_MEMFD_CREATE', language: 'c')

dependencies = [
    dependency('libargon2'),
    dependency('libavif'),
    dependency('libxml-2.0'),
    dependency('zlib'),
    dependency('threads'),
    cc.find_library('m'),
]

includes = include_directories(
    '.',
    'main',
    'Zend',
    'TSRM',
    'ext/intl',
    'ext/lexbor',
    'ext/uri/uriparser/include',
)

main_sources = [
    'main/debug_gdb_scripts.c',
    'main/explicit_bzero.c',
    'main/fastcgi.c',
    'main/fopen_wrappers.c',
    'main/getopt.c',
    'main/internal_functions_cli.c',
    'main/main.c',
    'main/network.c',
    'main/output.c',
    'main/php_content_types.c',
    'main/php_glob.c',
    'main/php_ini_builder.c',
    'main/php_ini.c',
    'main/php_odbc_utils.c',
    'main/php_open_temporary_file.c',
    'main/php_scandir.c',
    'main/php_syslog.c',
    'main/php_ticks.c',
    'main/php_variables.c',
    'main/reentrancy.c',
    'main/rfc1867.c',
    'main/safe_bcmp.c',
    'main/SAPI.c',
    'main/snprintf.c',
    'main/spprintf.c',
    'main/strlcat.c',
    'main/strlcpy.c',
    'main/streams/cast.c',
    'main/streams/filter.c',
    'main/streams/glob_wrapper.c',
    'main/streams/memory.c',
    'main/streams/mmap.c',
    'main/streams/plain_wrapper.c',
    'main/streams/streams.c',
    'main/streams/transports.c',
    'main/streams/userspace.c',
    'main/streams/xp_socket.c',
]

zend_sources = [
    'Zend/zend_alloc.c',
    'Zend/zend_API.c',
    'Zend/zend_ast.c',
    'Zend/zend_atomic.c',
    'Zend/zend_attributes.c',
    'Zend/zend_autoload.c',
    'Zend/zend_builtin_functions.c',
    'Zend/zend_call_stack.c',
    'Zend/zend_closures.c',
    'Zend/zend_compile.c',
    'Zend/zend_constants.c',
    'Zend/zend_cpuinfo.c',
    'Zend/zend_default_classes.c',
    'Zend/zend_dtrace.c',
    'Zend/zend_enum.c',
    'Zend/zend_exceptions.c',
    'Zend/zend_execute_API.c',
    'Zend/zend_execute.c',
    'Zend/zend_extensions.c',
    'Zend/zend_fibers.c',
    'Zend/zend_float.c',
    'Zend/zend_frameless_function.c',
    'Zend/zend_gc.c',
    'Zend/zend_gdb.c',
    'Zend/zend_generators.c',
    'Zend/zend_hash.c',
    'Zend/zend_highlight.c',
    'Zend/zend_hrtime.c',
    'Zend/zend_inheritance.c',
    'Zend/zend_ini_parser.c',
    'Zend/zend_ini_scanner.c',
    'Zend/zend_ini.c',
    'Zend/zend_interfaces.c',
    'Zend/zend_iterators.c',
    'Zend/zend_language_parser.c',
    'Zend/zend_language_scanner.c',
    'Zend/zend_lazy_objects.c',
    'Zend/zend_list.c',
    'Zend/zend_llist.c',
    'Zend/zend_max_execution_timer.c',
    'Zend/zend_multibyte.c',
    'Zend/zend_object_handlers.c',
    'Zend/zend_objects_API.c',
    'Zend/zend_objects.c',
    'Zend/zend_observer.c',
    'Zend/zend_opcode.c',
    'Zend/zend_operators.c',
    'Zend/zend_property_hooks.c',
    'Zend/zend_ptr_stack.c',
    'Zend/zend_signal.c',
    'Zend/zend_smart_str.c',
    'Zend/zend_sort.c',
    'Zend/zend_stack.c',
    'Zend/zend_stream.c',
    'Zend/zend_string.c',
    'Zend/zend_strtod.c',
    'Zend/zend_system_id.c',
    'Zend/zend_variables.c',
    'Zend/zend_virtual_cwd.c',
    'Zend/zend_vm_opcodes.c',
    'Zend/zend_weakrefs.c',
    'Zend/zend.c',
]

tsrm_sources = [
    'TSRM/TSRM.c'
]

sapi_cli_sources = [
    'sapi/cli/php_cli.c',
    'sapi/cli/php_cli_process_title.c',
    'sapi/cli/php_cli_server.c',
    'sapi/cli/php_http_parser.c',
    'sapi/cli/ps_title.c',
]

ext_date_sources = [
    'ext/date/php_date.c',
    'ext/date/lib/astro.c',
    'ext/date/lib/dow.c',
    'ext/date/lib/interval.c',
    'ext/date/lib/parse_date.c',
    'ext/date/lib/parse_iso_intervals.c',
    'ext/date/lib/parse_posix.c',
    'ext/date/lib/parse_tz.c',
    'ext/date/lib/timelib.c',
    'ext/date/lib/tm2unixtime.c',
    'ext/date/lib/unixtime2tm.c',
]

# EXTRA_FLAGS="-I./ext/hash/ -I./ext/hash/sha3/generic64lc -DKeccakP200_excluded -DKeccakP400_excluded -DKeccakP800_excluded"
ext_hash_sources = [
    'ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c',
    'ext/hash/sha3/generic64lc/KeccakHash.c',
    'ext/hash/sha3/generic64lc/KeccakSponge.c',
    'ext/hash/hash_adler32.c',
    'ext/hash/hash_crc32.c',
    'ext/hash/hash_fnv.c',
    'ext/hash/hash_gost.c',
    'ext/hash/hash_haval.c',
    'ext/hash/hash_joaat.c',
    'ext/hash/hash_md.c',
    'ext/hash/hash_murmur.c',
    'ext/hash/hash_ripemd.c',
    'ext/hash/hash_sha_ni.c',
    'ext/hash/hash_sha_sse2.c',
    'ext/hash/hash_sha.c',
    'ext/hash/hash_sha3.c',
    'ext/hash/hash_snefru.c',
    'ext/hash/hash_tiger.c',
    'ext/hash/hash_whirlpool.c',
    'ext/hash/hash_xxhash.c',
    'ext/hash/hash.c',
    'ext/hash/murmur/PMurHash.c',
    'ext/hash/murmur/PMurHash128.c',
]

#   EXTRA_FLAGS="-DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=1 -DU_HIDE_OBSOLETE_UTF_OLD_H=1 -Wno-write-strings -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS" cc_ ./ext/intl/*.c
ext_intl_sources = [
    'ext/intl/intl_convertcpp.cpp',
    'ext/intl/collator/collator_attr.cpp',
    'ext/intl/collator/collator_class.cpp',
    'ext/intl/collator/collator_compare.cpp',
    'ext/intl/collator/collator_convert.cpp',
    'ext/intl/collator/collator_create.cpp',
    'ext/intl/collator/collator_error.cpp',
    'ext/intl/collator/collator_is_numeric.cpp',
    'ext/intl/collator/collator_locale.cpp',
    'ext/intl/collator/collator_sort.cpp',
    'ext/intl/common/common_enum.cpp',
    'ext/intl/common/common_date.cpp',
    'ext/intl/common/common_error.cpp',
    'ext/intl/dateformat/dateformat_class.cpp',
    'ext/intl/converter/converter.cpp',
    'ext/intl/dateformat/dateformat.cpp',
    'ext/intl/dateformat/dateformat_attr.cpp',
    'ext/intl/dateformat/dateformat_attrcpp.cpp',
    'ext/intl/dateformat/dateformat_create.cpp',
    'ext/intl/dateformat/dateformat_data.cpp',
    'ext/intl/dateformat/dateformat_format.cpp',
    'ext/intl/dateformat/dateformat_format_object.cpp',
    'ext/intl/dateformat/dateformat_helpers.cpp',
    'ext/intl/dateformat/dateformat_parse.cpp',
    'ext/intl/dateformat/datepatterngenerator_class.cpp',
    'ext/intl/dateformat/datepatterngenerator_methods.cpp',
    'ext/intl/formatter/formatter_class.cpp',
    'ext/intl/grapheme/grapheme_string.cpp',
    'ext/intl/grapheme/grapheme_util.cpp',
    'ext/intl/msgformat/msgformat_helpers.cpp',
    'ext/intl/rangeformatter/rangeformatter_class.cpp',
    'ext/intl/timezone/timezone_class.cpp',
    'ext/intl/timezone/timezone_methods.cpp',
    'ext/intl/calendar/calendar_class.cpp',
    'ext/intl/calendar/calendar_methods.cpp',
    'ext/intl/calendar/gregoriancalendar_methods.cpp',
    'ext/intl/formatter/formatter_attr.cpp',
    'ext/intl/formatter/formatter_data.cpp',
    'ext/intl/formatter/formatter_format.cpp',
    'ext/intl/formatter/formatter_main.cpp',
    'ext/intl/formatter/formatter_parse.cpp',
    'ext/intl/msgformat/msgformat_attr.cpp',
    'ext/intl/msgformat/msgformat_class.cpp',
    'ext/intl/msgformat/msgformat_data.cpp',
    'ext/intl/msgformat/msgformat_format.cpp',
    'ext/intl/msgformat/msgformat_parse.cpp',
    'ext/intl/msgformat/msgformat.cpp',
    'ext/intl/normalizer/normalizer_class.cpp',
    'ext/intl/normalizer/normalizer_normalize.cpp',
    'ext/intl/breakiterator/breakiterator_class.cpp',
    'ext/intl/breakiterator/breakiterator_iterators.cpp',
    'ext/intl/breakiterator/breakiterator_methods.cpp',
    'ext/intl/breakiterator/rulebasedbreakiterator_methods.cpp',
    'ext/intl/breakiterator/codepointiterator_internal.cpp',
    'ext/intl/breakiterator/codepointiterator_methods.cpp',
    'ext/intl/listformatter/listformatter_class.cpp',
    'ext/intl/transliterator/transliterator_class.cpp',
    'ext/intl/transliterator/transliterator_methods.cpp',
    'ext/intl/idn/idn.cpp',
    'ext/intl/locale/locale_class.cpp',
    'ext/intl/locale/locale_methods.cpp',
    'ext/intl/locale/locale.cpp',
    'ext/intl/resourcebundle/resourcebundle_class.cpp',
    'ext/intl/resourcebundle/resourcebundle_iterator.cpp',
    'ext/intl/resourcebundle/resourcebundle.cpp',
    'ext/intl/spoofchecker/spoofchecker_class.cpp',
    'ext/intl/spoofchecker/spoofchecker_create.cpp',
    'ext/intl/spoofchecker/spoofchecker_main.cpp',
    'ext/intl/uchar/uchar.cpp',
]

ext_json_sources = [
    'ext/json/json.c',
    'ext/json/json_encoder.c',
    'ext/json/json_parser.tab.c',
    'ext/json/json_scanner.c',
]

ext_lexbor_sources = [
    'ext/lexbor/php_lexbor.c',
    'ext/lexbor/lexbor/core/array.c',
    'ext/lexbor/lexbor/core/array_obj.c',
    'ext/lexbor/lexbor/core/avl.c',
    'ext/lexbor/lexbor/core/bst.c',
    'ext/lexbor/lexbor/core/bst_map.c',
    'ext/lexbor/lexbor/core/conv.c',
    'ext/lexbor/lexbor/core/diyfp.c',
    'ext/lexbor/lexbor/core/dobject.c',
    'ext/lexbor/lexbor/core/dtoa.c',
    'ext/lexbor/lexbor/core/hash.c',
    'ext/lexbor/lexbor/core/in.c',
    'ext/lexbor/lexbor/core/mem.c',
    'ext/lexbor/lexbor/core/mraw.c',
    'ext/lexbor/lexbor/core/plog.c',
    'ext/lexbor/lexbor/core/print.c',
    'ext/lexbor/lexbor/core/serialize.c',
    'ext/lexbor/lexbor/core/shs.c',
    'ext/lexbor/lexbor/core/str.c',
    'ext/lexbor/lexbor/core/strtod.c',
    'ext/lexbor/lexbor/core/utils.c',
    'ext/lexbor/lexbor/css/css.c',
    'ext/lexbor/lexbor/css/log.c',
    'ext/lexbor/lexbor/css/parser.c',
    'ext/lexbor/lexbor/css/state.c',
    'ext/lexbor/lexbor/css/selectors/pseudo.c',
    'ext/lexbor/lexbor/css/selectors/pseudo_state.c',
    'ext/lexbor/lexbor/css/selectors/selector.c',
    'ext/lexbor/lexbor/css/selectors/selectors.c',
    'ext/lexbor/lexbor/css/selectors/state.c',
    'ext/lexbor/lexbor/css/syntax/anb.c',
    'ext/lexbor/lexbor/css/syntax/parser.c',
    'ext/lexbor/lexbor/css/syntax/state.c',
    'ext/lexbor/lexbor/css/syntax/syntax.c',
    'ext/lexbor/lexbor/css/syntax/token.c',
    'ext/lexbor/lexbor/css/syntax/tokenizer.c',
    'ext/lexbor/lexbor/css/syntax/tokenizer/error.c',
    'ext/lexbor/lexbor/dom/collection.c',
    'ext/lexbor/lexbor/dom/exception.c',
    'ext/lexbor/lexbor/dom/interface.c',
    'ext/lexbor/lexbor/dom/interfaces/attr.c',
    'ext/lexbor/lexbor/dom/interfaces/cdata_section.c',
    'ext/lexbor/lexbor/dom/interfaces/character_data.c',
    'ext/lexbor/lexbor/dom/interfaces/comment.c',
    'ext/lexbor/lexbor/dom/interfaces/document.c',
    'ext/lexbor/lexbor/dom/interfaces/document_fragment.c',
    'ext/lexbor/lexbor/dom/interfaces/document_type.c',
    'ext/lexbor/lexbor/dom/interfaces/element.c',
    'ext/lexbor/lexbor/dom/interfaces/event_target.c',
    'ext/lexbor/lexbor/dom/interfaces/node.c',
    'ext/lexbor/lexbor/dom/interfaces/processing_instruction.c',
    'ext/lexbor/lexbor/dom/interfaces/shadow_root.c',
    'ext/lexbor/lexbor/dom/interfaces/text.c',
    'ext/lexbor/lexbor/encoding/decode.c',
    'ext/lexbor/lexbor/encoding/encode.c',
    'ext/lexbor/lexbor/encoding/encoding.c',
    'ext/lexbor/lexbor/encoding/multi.c',
    'ext/lexbor/lexbor/encoding/range.c',
    'ext/lexbor/lexbor/encoding/res.c',
    'ext/lexbor/lexbor/encoding/single.c',
    'ext/lexbor/lexbor/html/encoding.c',
    'ext/lexbor/lexbor/html/interface.c',
    'ext/lexbor/lexbor/html/parser.c',
    'ext/lexbor/lexbor/html/tree.c',
    'ext/lexbor/lexbor/html/token.c',
    'ext/lexbor/lexbor/html/token_attr.c',
    'ext/lexbor/lexbor/html/tokenizer.c',
    'ext/lexbor/lexbor/html/interfaces/anchor_element.c',
    'ext/lexbor/lexbor/html/interfaces/area_element.c',
    'ext/lexbor/lexbor/html/interfaces/audio_element.c',
    'ext/lexbor/lexbor/html/interfaces/base_element.c',
    'ext/lexbor/lexbor/html/interfaces/body_element.c',
    'ext/lexbor/lexbor/html/interfaces/br_element.c',
    'ext/lexbor/lexbor/html/interfaces/button_element.c',
    'ext/lexbor/lexbor/html/interfaces/canvas_element.c',
    'ext/lexbor/lexbor/html/interfaces/d_list_element.c',
    'ext/lexbor/lexbor/html/interfaces/data_element.c',
    'ext/lexbor/lexbor/html/interfaces/data_list_element.c',
    'ext/lexbor/lexbor/html/interfaces/details_element.c',
    'ext/lexbor/lexbor/html/interfaces/dialog_element.c',
    'ext/lexbor/lexbor/html/interfaces/directory_element.c',
    'ext/lexbor/lexbor/html/interfaces/div_element.c',
    'ext/lexbor/lexbor/html/interfaces/document.c',
    'ext/lexbor/lexbor/html/interfaces/element.c',
    'ext/lexbor/lexbor/html/interfaces/embed_element.c',
    'ext/lexbor/lexbor/html/interfaces/field_set_element.c',
    'ext/lexbor/lexbor/html/interfaces/font_element.c',
    'ext/lexbor/lexbor/html/interfaces/form_element.c',
    'ext/lexbor/lexbor/html/interfaces/frame_element.c',
    'ext/lexbor/lexbor/html/interfaces/frame_set_element.c',
    'ext/lexbor/lexbor/html/interfaces/head_element.c',
    'ext/lexbor/lexbor/html/interfaces/heading_element.c',
    'ext/lexbor/lexbor/html/interfaces/hr_element.c',
    'ext/lexbor/lexbor/html/interfaces/html_element.c',
    'ext/lexbor/lexbor/html/interfaces/iframe_element.c',
    'ext/lexbor/lexbor/html/interfaces/image_element.c',
    'ext/lexbor/lexbor/html/interfaces/input_element.c',
    'ext/lexbor/lexbor/html/interfaces/label_element.c',
    'ext/lexbor/lexbor/html/interfaces/legend_element.c',
    'ext/lexbor/lexbor/html/interfaces/li_element.c',
    'ext/lexbor/lexbor/html/interfaces/link_element.c',
    'ext/lexbor/lexbor/html/interfaces/map_element.c',
    'ext/lexbor/lexbor/html/interfaces/marquee_element.c',
    'ext/lexbor/lexbor/html/interfaces/media_element.c',
    'ext/lexbor/lexbor/html/interfaces/menu_element.c',
    'ext/lexbor/lexbor/html/interfaces/meta_element.c',
    'ext/lexbor/lexbor/html/interfaces/meter_element.c',
    'ext/lexbor/lexbor/html/interfaces/mod_element.c',
    'ext/lexbor/lexbor/html/interfaces/o_list_element.c',
    'ext/lexbor/lexbor/html/interfaces/object_element.c',
    'ext/lexbor/lexbor/html/interfaces/opt_group_element.c',
    'ext/lexbor/lexbor/html/interfaces/option_element.c',
    'ext/lexbor/lexbor/html/interfaces/output_element.c',
    'ext/lexbor/lexbor/html/interfaces/paragraph_element.c',
    'ext/lexbor/lexbor/html/interfaces/param_element.c',
    'ext/lexbor/lexbor/html/interfaces/picture_element.c',
    'ext/lexbor/lexbor/html/interfaces/pre_element.c',
    'ext/lexbor/lexbor/html/interfaces/progress_element.c',
    'ext/lexbor/lexbor/html/interfaces/quote_element.c',
    'ext/lexbor/lexbor/html/interfaces/script_element.c',
    'ext/lexbor/lexbor/html/interfaces/select_element.c',
    'ext/lexbor/lexbor/html/interfaces/slot_element.c',
    'ext/lexbor/lexbor/html/interfaces/source_element.c',
    'ext/lexbor/lexbor/html/interfaces/span_element.c',
    'ext/lexbor/lexbor/html/interfaces/style_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_caption_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_cell_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_col_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_row_element.c',
    'ext/lexbor/lexbor/html/interfaces/table_section_element.c',
    'ext/lexbor/lexbor/html/interfaces/template_element.c',
    'ext/lexbor/lexbor/html/interfaces/text_area_element.c',
    'ext/lexbor/lexbor/html/interfaces/time_element.c',
    'ext/lexbor/lexbor/html/interfaces/title_element.c',
    'ext/lexbor/lexbor/html/interfaces/track_element.c',
    'ext/lexbor/lexbor/html/interfaces/u_list_element.c',
    'ext/lexbor/lexbor/html/interfaces/unknown_element.c',
    'ext/lexbor/lexbor/html/interfaces/video_element.c',
    'ext/lexbor/lexbor/html/interfaces/window.c',
    'ext/lexbor/lexbor/html/tokenizer/error.c',
    'ext/lexbor/lexbor/html/tokenizer/state.c',
    'ext/lexbor/lexbor/html/tokenizer/state_comment.c',
    'ext/lexbor/lexbor/html/tokenizer/state_doctype.c',
    'ext/lexbor/lexbor/html/tokenizer/state_rawtext.c',
    'ext/lexbor/lexbor/html/tokenizer/state_rcdata.c',
    'ext/lexbor/lexbor/html/tokenizer/state_script.c',
    'ext/lexbor/lexbor/html/tree/active_formatting.c',
    'ext/lexbor/lexbor/html/tree/error.c',
    'ext/lexbor/lexbor/html/tree/open_elements.c',
    'ext/lexbor/lexbor/html/tree/template_insertion.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/after_after_body.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/after_after_frameset.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/after_body.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/after_frameset.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/after_head.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/before_head.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/before_html.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/foreign_content.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_body.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_caption.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_cell.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_column_group.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_frameset.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_head.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_head_noscript.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_row.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_select.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_select_in_table.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_table.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_table_body.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_table_text.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/in_template.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/initial.c',
    'ext/lexbor/lexbor/html/tree/insertion_mode/text.c',
    'ext/lexbor/lexbor/ns/ns.c',
    'ext/lexbor/lexbor/ports/posix/lexbor/core/memory.c',
    'ext/lexbor/lexbor/punycode/punycode.c',
    'ext/lexbor/lexbor/tag/tag.c',
    'ext/lexbor/lexbor/unicode/idna.c',
    'ext/lexbor/lexbor/unicode/unicode.c',
    'ext/lexbor/lexbor/url/url.c',
]

ext_libxml_sources = [
    'ext/libxml/image_svg.c',
    'ext/libxml/libxml.c',
    'ext/libxml/mime_sniff.c',
]

ext_mysqli_sources = [
    'ext/mysqli/mysqli.c',
    'ext/mysqli/mysqli_api.c',
    'ext/mysqli/mysqli_driver.c',
    'ext/mysqli/mysqli_exception.c',
    'ext/mysqli/mysqli_nonapi.c',
    'ext/mysqli/mysqli_prop.c',
    'ext/mysqli/mysqli_report.c',
    'ext/mysqli/mysqli_result_iterator.c',
    'ext/mysqli/mysqli_warning.c',
]

ext_mysqlnd_sources = [
    'ext/mysqlnd/mysqlnd_alloc.c',
    'ext/mysqlnd/mysqlnd_auth.c',
    'ext/mysqlnd/mysqlnd_block_alloc.c',
    'ext/mysqlnd/mysqlnd_charset.c',
    'ext/mysqlnd/mysqlnd_commands.c',
    'ext/mysqlnd/mysqlnd_connection.c',
    'ext/mysqlnd/mysqlnd_debug.c',
    'ext/mysqlnd/mysqlnd_driver.c',
    'ext/mysqlnd/mysqlnd_ext_plugin.c',
    'ext/mysqlnd/mysqlnd_loaddata.c',
    'ext/mysqlnd/mysqlnd_plugin.c',
    'ext/mysqlnd/mysqlnd_protocol_frame_codec.c',
    'ext/mysqlnd/mysqlnd_ps.c',
    'ext/mysqlnd/mysqlnd_ps_codec.c',
    'ext/mysqlnd/mysqlnd_read_buffer.c',
    'ext/mysqlnd/mysqlnd_result.c',
    'ext/mysqlnd/mysqlnd_result_meta.c',
    'ext/mysqlnd/mysqlnd_reverse_api.c',
    'ext/mysqlnd/mysqlnd_statistics.c',
    'ext/mysqlnd/mysqlnd_vio.c',
    'ext/mysqlnd/mysqlnd_wireprotocol.c',
    'ext/mysqlnd/php_mysqlnd.c',
]

ext_opcache_sources = [
    'ext/opcache/ZendAccelerator.c',
    'ext/opcache/shared_alloc_mmap.c',
    'ext/opcache/shared_alloc_posix.c',
    'ext/opcache/shared_alloc_shm.c',
    'ext/opcache/zend_accelerator_api.c',
    'ext/opcache/zend_accelerator_blacklist.c',
    'ext/opcache/zend_accelerator_debug.c',
    'ext/opcache/zend_accelerator_hash.c',
    'ext/opcache/zend_accelerator_module.c',
    'ext/opcache/zend_accelerator_util_funcs.c',
    'ext/opcache/zend_file_cache.c',
    'ext/opcache/zend_persist.c',
    'ext/opcache/zend_persist_calc.c',
    'ext/opcache/zend_shared_alloc.c',
]

#   EXTRA_FLAGS="-I./ext/pcre -Wno-implicit-fallthrough -DHAVE_CONFIG_H -DHAVE_MEMMOVE" cc_ \
ext_pcre_sources = [
    'ext/pcre/pcre2lib/pcre2_auto_possess.c',
    'ext/pcre/pcre2lib/pcre2_chartables.c',
    'ext/pcre/pcre2lib/pcre2_chkdint.c',
    'ext/pcre/pcre2lib/pcre2_compile.c',
    'ext/pcre/pcre2lib/pcre2_config.c',
    'ext/pcre/pcre2lib/pcre2_context.c',
    'ext/pcre/pcre2lib/pcre2_convert.c',
    'ext/pcre/pcre2lib/pcre2_dfa_match.c',
    'ext/pcre/pcre2lib/pcre2_error.c',
    'ext/pcre/pcre2lib/pcre2_extuni.c',
    'ext/pcre/pcre2lib/pcre2_find_bracket.c',
    'ext/pcre/pcre2lib/pcre2_jit_compile.c',
    'ext/pcre/pcre2lib/pcre2_maketables.c',
    'ext/pcre/pcre2lib/pcre2_match_data.c',
    'ext/pcre/pcre2lib/pcre2_match.c',
    'ext/pcre/pcre2lib/pcre2_newline.c',
    'ext/pcre/pcre2lib/pcre2_ord2utf.c',
    'ext/pcre/pcre2lib/pcre2_pattern_info.c',
    'ext/pcre/pcre2lib/pcre2_script_run.c',
    'ext/pcre/pcre2lib/pcre2_serialize.c',
    'ext/pcre/pcre2lib/pcre2_string_utils.c',
    'ext/pcre/pcre2lib/pcre2_study.c',
    'ext/pcre/pcre2lib/pcre2_substitute.c',
    'ext/pcre/pcre2lib/pcre2_substring.c',
    'ext/pcre/pcre2lib/pcre2_tables.c',
    'ext/pcre/pcre2lib/pcre2_ucd.c',
    'ext/pcre/pcre2lib/pcre2_valid_utf.c',
    'ext/pcre/pcre2lib/pcre2_xclass.c',
    'ext/pcre/php_pcre.c',
]


ext_readline_sources = [
    'ext/readline/readline.c',
    'ext/readline/readline_cli.c',
]

ext_random_sources = [
    'ext/random/csprng.c',
    'ext/random/engine_mt19937.c',
    'ext/random/engine_pcgoneseq128xslrr64.c',
    'ext/random/engine_secure.c',
    'ext/random/engine_user.c',
    'ext/random/engine_xoshiro256starstar.c',
    'ext/random/gammasection.c',
    'ext/random/random.c',
    'ext/random/randomizer.c',
    'ext/random/zend_utils.c',
]

ext_reflection_sources = [
    'ext/reflection/php_reflection.c',
]

ext_spl_sources = [
    'ext/spl/php_spl.c',
    'ext/spl/spl_array.c',
    'ext/spl/spl_directory.c',
    'ext/spl/spl_dllist.c',
    'ext/spl/spl_exceptions.c',
    'ext/spl/spl_fixedarray.c',
    'ext/spl/spl_functions.c',
    'ext/spl/spl_heap.c',
    'ext/spl/spl_iterators.c',
    'ext/spl/spl_observer.c',
]

ext_standard_sources = [
    'ext/standard/array.c',
    'ext/standard/assert.c',
    'ext/standard/base64.c',
    'ext/standard/basic_functions.c',
    'ext/standard/browscap.c',
    'ext/standard/crc32.c',
    'ext/standard/crc32_x86.c',
    'ext/standard/credits.c',
    'ext/standard/crypt.c',
    'ext/standard/crypt_blowfish.c',
    'ext/standard/crypt_freesec.c',
    'ext/standard/crypt_sha256.c',
    'ext/standard/crypt_sha512.c',
    'ext/standard/css.c',
    'ext/standard/datetime.c',
    'ext/standard/dir.c',
    'ext/standard/dl.c',
    'ext/standard/dns.c',
    'ext/standard/exec.c',
    'ext/standard/file.c',
    'ext/standard/filestat.c',
    'ext/standard/filters.c',
    'ext/standard/flock_compat.c',
    'ext/standard/formatted_print.c',
    'ext/standard/fsock.c',
    'ext/standard/ftok.c',
    'ext/standard/ftp_fopen_wrapper.c',
    'ext/standard/head.c',
    'ext/standard/hrtime.c',
    'ext/standard/html.c',
    'ext/standard/http.c',
    'ext/standard/http_fopen_wrapper.c',
    'ext/standard/image.c',
    'ext/standard/incomplete_class.c',
    'ext/standard/info.c',
    'ext/standard/iptc.c',
    'ext/standard/levenshtein.c',
    'ext/standard/link.c',
    'ext/standard/mail.c',
    'ext/standard/math.c',
    'ext/standard/md5.c',
    'ext/standard/metaphone.c',
    'ext/standard/microtime.c',
    'ext/standard/net.c',
    'ext/standard/pack.c',
    'ext/standard/pageinfo.c',
    'ext/standard/password.c',
    'ext/standard/php_crypt_r.c',
    'ext/standard/php_fopen_wrapper.c',
    'ext/standard/proc_open.c',
    'ext/standard/quot_print.c',
    'ext/standard/scanf.c',
    'ext/standard/sha1.c',
    'ext/standard/soundex.c',
    'ext/standard/streamsfuncs.c',
    'ext/standard/string.c',
    'ext/standard/strnatcmp.c',
    'ext/standard/syslog.c',
    'ext/standard/type.c',
    'ext/standard/uniqid.c',
    'ext/standard/url.c',
    'ext/standard/url_scanner_ex.c',
    'ext/standard/user_filters.c',
    'ext/standard/uuencode.c',
    'ext/standard/var.c',
    'ext/standard/var_unserializer.c',
    'ext/standard/versioning.c',
]

ext_uri_sources = [
    'ext/uri/php_uri.c',
    'ext/uri/php_uri_common.c',
    'ext/uri/uri_parser_php_parse_url.c',
    'ext/uri/uri_parser_rfc3986.c',
    'ext/uri/uri_parser_whatwg.c',
    'ext/uri/uriparser/src/UriCommon.c',
    'ext/uri/uriparser/src/UriCompare.c',
    'ext/uri/uriparser/src/UriCopy.c',
    'ext/uri/uriparser/src/UriEscape.c',
    'ext/uri/uriparser/src/UriFile.c',
    'ext/uri/uriparser/src/UriIp4.c',
    'ext/uri/uriparser/src/UriIp4Base.c',
    'ext/uri/uriparser/src/UriMemory.c',
    'ext/uri/uriparser/src/UriNormalize.c',
    'ext/uri/uriparser/src/UriNormalizeBase.c',
    'ext/uri/uriparser/src/UriParse.c',
    'ext/uri/uriparser/src/UriParseBase.c',
    'ext/uri/uriparser/src/UriQuery.c',
    'ext/uri/uriparser/src/UriRecompose.c',
    'ext/uri/uriparser/src/UriResolve.c',
    'ext/uri/uriparser/src/UriSetFragment.c',
    'ext/uri/uriparser/src/UriSetHostAuto.c',
    'ext/uri/uriparser/src/UriSetHostCommon.c',
    'ext/uri/uriparser/src/UriSetHostIp4.c',
    'ext/uri/uriparser/src/UriSetHostIp6.c',
    'ext/uri/uriparser/src/UriSetHostIpFuture.c',
    'ext/uri/uriparser/src/UriSetHostRegName.c',
    'ext/uri/uriparser/src/UriSetPath.c',
    'ext/uri/uriparser/src/UriSetPort.c',
    'ext/uri/uriparser/src/UriSetQuery.c',
    'ext/uri/uriparser/src/UriSetScheme.c',
    'ext/uri/uriparser/src/UriSetUserInfo.c',
    'ext/uri/uriparser/src/UriShorten.c',
    'ext/uri/uriparser/src/UriVersion.c',
]

cli_sources = [
    main_sources,
    zend_sources,
    tsrm_sources,
    sapi_cli_sources,
    ext_date_sources,
#    ext_hash_sources,
    ext_intl_sources,
    ext_json_sources,
    ext_lexbor_sources,
    ext_libxml_sources,
    ext_mysqli_sources,
    ext_mysqlnd_sources,
    ext_opcache_sources,
#    ext_pcre_sources,
    ext_readline_sources,
    ext_random_sources,
    ext_reflection_sources,
    ext_spl_sources,
    ext_standard_sources,
    ext_uri_sources,
]

# -I./ext/hash/ -I./ext/hash/sha3/generic64lc
hash_objs = static_library(
    'hash_objs',
    ext_hash_sources,
    c_args: ['-DKeccakP200_excluded', '-DKeccakP400_excluded', '-DKeccakP800_excluded'],
    include_directories: [includes, 'ext/hash/sha3/generic64lc'],
    build_by_default: false,
)

pcre_objs = static_library(
    'pcre_objs',
    ext_pcre_sources,
    c_args: ['-DHAVE_CONFIG_H', '-DHAVE_MEMMOVE'],
    include_directories: [includes],
    build_by_default: false,
)

link_whole = [hash_objs, pcre_objs]

cli = executable(
    'punk',
    cli_sources,
    dependencies : dependencies,
    include_directories : includes,
    link_whole: link_whole,
    install : false,
)
#
#test('basic', cli)

