#!/usr/bin/env bash
# shellcheck disable=SC2046
# shellcheck disable=SC2086

set -euo pipefail

set -a
. $(dirname $0)/.env
set +a

# clion can't cope with compilers of >1 word like "ccache cc"
# I could fix this with a wrapper, but this is simpler for now
export CC=clang
export CXX=clang++

exec meson "$@"
