main_sources = files(
    'debug_gdb_scripts.c',
    'explicit_bzero.c',
    'fastcgi.c',
    'fopen_wrappers.c',
    'getopt.c',
    'internal_functions_cli.c',
    'main.c',
    'network.c',
    'output.c',
    'php_content_types.c',
    'php_glob.c',
    'php_ini_builder.c',
    'php_ini.c',
    'php_odbc_utils.c',
    'php_open_temporary_file.c',
    'php_scandir.c',
    'php_syslog.c',
    'php_ticks.c',
    'php_variables.c',
    'reentrancy.c',
    'rfc1867.c',
    'safe_bcmp.c',
    'SAPI.c',
    'snprintf.c',
    'spprintf.c',
    'strlcat.c',
    'strlcpy.c',
    'streams/cast.c',
    'streams/filter.c',
    'streams/glob_wrapper.c',
    'streams/memory.c',
    'streams/mmap.c',
    'streams/plain_wrapper.c',
    'streams/streams.c',
    'streams/transports.c',
    'streams/userspace.c',
    'streams/xp_socket.c',
)

main_objs = static_library(
    'main_objs',
    main_sources,
    c_args : [],
    include_directories : [includes],
    build_by_default : false,
)

install_headers(
    'SAPI.h',
    'build-defs.h',
    'fastcgi.h',
    'fopen_wrappers.h',
    'http_status_codes.h',
    'main_arginfo.h',
    'php.h',
    'php_compat.h',
    'php_config.h',
    'php_content_types.h',
    'php_getopt.h',
    'php_globals.h',
    'php_ini.h',
    'php_ini_builder.h',
    'php_main.h',
    'php_memory_streams.h',
    'php_network.h',
    'php_odbc_utils.h',
    'php_open_temporary_file.h',
    'php_output.h',
    'php_reentrancy.h',
    'php_scandir.h',
    'php_streams.h',
    'php_syslog.h',
    'php_ticks.h',
    'php_variables.h',
    'php_version.h',
    'rfc1867.h',
    'snprintf.h',
    'spprintf.h',
    subdir : 'main',
)

install_headers(
    'streams/php_stream_context.h',
    'streams/php_stream_filter_api.h',
    'streams/php_stream_glob_wrapper.h',
    'streams/php_stream_mmap.h',
    'streams/php_stream_plain_wrapper.h',
    'streams/php_stream_transport.h',
    'streams/php_stream_userspace.h',
    'streams/php_streams_int.h',
    'streams/userspace_arginfo.h',
    subdir : 'main/streams',
)
