zend_sources = files(
    'zend_alloc.c',
    'zend_API.c',
    'zend_ast.c',
    'zend_atomic.c',
    'zend_attributes.c',
    'zend_autoload.c',
    'zend_builtin_functions.c',
    'zend_call_stack.c',
    'zend_closures.c',
    'zend_compile.c',
    'zend_constants.c',
    'zend_cpuinfo.c',
    'zend_default_classes.c',
    'zend_dtrace.c',
    'zend_enum.c',
    'zend_exceptions.c',
    'zend_execute_API.c',
    'zend_execute.c',
    'zend_extensions.c',
    'zend_fibers.c',
    'zend_float.c',
    'zend_frameless_function.c',
    'zend_gc.c',
    'zend_gdb.c',
    'zend_generators.c',
    'zend_hash.c',
    'zend_highlight.c',
    'zend_hrtime.c',
    'zend_inheritance.c',
    'zend_ini_parser.c',
    'zend_ini_scanner.c',
    'zend_ini.c',
    'zend_interfaces.c',
    'zend_iterators.c',
    'zend_language_parser.c',
    'zend_language_scanner.c',
    'zend_lazy_objects.c',
    'zend_list.c',
    'zend_llist.c',
    'zend_multibyte.c',
    'zend_object_handlers.c',
    'zend_objects_API.c',
    'zend_objects.c',
    'zend_observer.c',
    'zend_opcode.c',
    'zend_operators.c',
    'zend_property_hooks.c',
    'zend_ptr_stack.c',
    'zend_signal.c',
    'zend_smart_str.c',
    'zend_sort.c',
    'zend_stack.c',
    'zend_stream.c',
    'zend_string.c',
    'zend_strtod.c',
    'zend_system_id.c',
    'zend_variables.c',
    'zend_virtual_cwd.c',
    'zend_vm_opcodes.c',
    'zend_weakrefs.c',
    'zend.c',
    'Optimizer/block_pass.c',
    'Optimizer/compact_literals.c',
    'Optimizer/compact_vars.c',
    'Optimizer/dce.c',
    'Optimizer/dfa_pass.c',
    'Optimizer/escape_analysis.c',
    'Optimizer/nop_removal.c',
    'Optimizer/optimize_func_calls.c',
    'Optimizer/optimize_temp_vars_5.c',
    'Optimizer/pass1.c',
    'Optimizer/pass3.c',
    'Optimizer/sccp.c',
    'Optimizer/scdf.c',
#    'Optimizer/ssa_integrity.c',
    'Optimizer/zend_call_graph.c',
    'Optimizer/zend_cfg.c',
    'Optimizer/zend_dfg.c',
    'Optimizer/zend_dump.c',
    'Optimizer/zend_func_info.c',
    'Optimizer/zend_inference.c',
    'Optimizer/zend_optimizer.c',
    'Optimizer/zend_ssa.c',

    # works, but is arch and OS specific, so we disable fiber asm for now
    # 'asm/jump_arm64_aapcs_elf_gas.S',
    # 'asm/make_arm64_aapcs_elf_gas.S',

    # broken if compiled while not enabled
    #    'zend_max_execution_timer.c',
)

zend_objs = static_library(
    'zend_objs',
    zend_sources,
    c_args: [],
    include_directories: [includes],
    build_by_default: false,
)
