ext_intl_sources = files(
    'intl_convert.c',
    'intl_error.c',
    'php_intl.c',
    'intl_convertcpp.cpp',
    'collator/collator_attr.cpp',
    'collator/collator_class.cpp',
    'collator/collator_compare.cpp',
    'collator/collator_convert.cpp',
    'collator/collator_create.cpp',
    'collator/collator_error.cpp',
    'collator/collator_is_numeric.cpp',
    'collator/collator_locale.cpp',
    'collator/collator_sort.cpp',
    'common/common_enum.cpp',
    'common/common_date.cpp',
    'common/common_error.cpp',
    'dateformat/dateformat_class.cpp',
    'converter/converter.cpp',
    'dateformat/dateformat.cpp',
    'dateformat/dateformat_attr.cpp',
    'dateformat/dateformat_attrcpp.cpp',
    'dateformat/dateformat_create.cpp',
    'dateformat/dateformat_data.cpp',
    'dateformat/dateformat_format.cpp',
    'dateformat/dateformat_format_object.cpp',
    'dateformat/dateformat_helpers.cpp',
    'dateformat/dateformat_parse.cpp',
    'dateformat/datepatterngenerator_class.cpp',
    'dateformat/datepatterngenerator_methods.cpp',
    'formatter/formatter_class.cpp',
    'grapheme/grapheme_string.cpp',
    'grapheme/grapheme_util.cpp',
    'msgformat/msgformat_helpers.cpp',
    'rangeformatter/rangeformatter_class.cpp',
    'timezone/timezone_class.cpp',
    'timezone/timezone_methods.cpp',
    'calendar/calendar_class.cpp',
    'calendar/calendar_methods.cpp',
    'calendar/gregoriancalendar_methods.cpp',
    'formatter/formatter_attr.cpp',
    'formatter/formatter_data.cpp',
    'formatter/formatter_format.cpp',
    'formatter/formatter_main.cpp',
    'formatter/formatter_parse.cpp',
    'msgformat/msgformat_attr.cpp',
    'msgformat/msgformat_class.cpp',
    'msgformat/msgformat_data.cpp',
    'msgformat/msgformat_format.cpp',
    'msgformat/msgformat_parse.cpp',
    'msgformat/msgformat.cpp',
    'normalizer/normalizer_class.cpp',
    'normalizer/normalizer_normalize.cpp',
    'breakiterator/breakiterator_class.cpp',
    'breakiterator/breakiterator_iterators.cpp',
    'breakiterator/breakiterator_methods.cpp',
    'breakiterator/rulebasedbreakiterator_methods.cpp',
    'breakiterator/codepointiterator_internal.cpp',
    'breakiterator/codepointiterator_methods.cpp',
    'listformatter/listformatter_class.cpp',
    'transliterator/transliterator_class.cpp',
    'transliterator/transliterator_methods.cpp',
    'idn/idn.cpp',
    'locale/locale_class.cpp',
    'locale/locale_methods.cpp',
    'locale/locale.cpp',
    'resourcebundle/resourcebundle_class.cpp',
    'resourcebundle/resourcebundle_iterator.cpp',
    'resourcebundle/resourcebundle.cpp',
    'spoofchecker/spoofchecker_class.cpp',
    'spoofchecker/spoofchecker_create.cpp',
    'spoofchecker/spoofchecker_main.cpp',
    'uchar/uchar.cpp',
)

# used by both C and C++
ext_intl_c_args = [
    '-Wno-write-strings',
    '-DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=1',
    '-DU_HIDE_OBSOLETE_UTF_OLD_H=1',
    '-D__STDC_LIMIT_MACROS',
    '-D__STDC_CONSTANT_MACROS',
    '-D__STDC_FORMAT_MACROS'
]

ext_intl_objs = static_library(
    'ext_intl_objs',
    ext_intl_sources,
    c_args : ext_intl_c_args,
    cpp_args : ext_intl_c_args,
    include_directories : [includes],
    build_by_default : false,
)

shared_module(
    'intl',
    [ext_intl_sources],
    name_prefix: '',
    c_args : ext_intl_c_args,
    cpp_args : ext_intl_c_args,
    include_directories : [includes],
    install : true,
)
