ext_mysqlnd_sources = files(
    'mysqlnd_alloc.c',
    'mysqlnd_auth.c',
    'mysqlnd_block_alloc.c',
    'mysqlnd_charset.c',
    'mysqlnd_commands.c',
    'mysqlnd_connection.c',
    'mysqlnd_debug.c',
    'mysqlnd_driver.c',
    'mysqlnd_ext_plugin.c',
    'mysqlnd_loaddata.c',
    'mysqlnd_plugin.c',
    'mysqlnd_protocol_frame_codec.c',
    'mysqlnd_ps.c',
    'mysqlnd_ps_codec.c',
    'mysqlnd_read_buffer.c',
    'mysqlnd_result.c',
    'mysqlnd_result_meta.c',
    'mysqlnd_reverse_api.c',
    'mysqlnd_statistics.c',
    'mysqlnd_vio.c',
    'mysqlnd_wireprotocol.c',
    'php_mysqlnd.c',
)

shared_module(
    'mysqlnd',
    [ext_mysqlnd_sources],
    name_prefix: '',
    c_args : [],
    include_directories : [includes],
    install : true,
)
