ext_gd_sources = files(
    'gd.c',
    'libgd/gd_avif.c',
    'libgd/gd_bmp.c',
    'libgd/gd_color_match.c',
    'libgd/gd_crop.c',
    'libgd/gd_filter.c',
    'libgd/gd_gd.c',
    'libgd/gd_gd2.c',
    'libgd/gd_gif_in.c',
    'libgd/gd_gif_out.c',
    'libgd/gd_interpolation.c',
    'libgd/gd_io_dp.c',
    'libgd/gd_io_file.c',
    'libgd/gd_io_ss.c',
    'libgd/gd_io.c',
    'libgd/gd_jpeg.c',
    'libgd/gd_matrix.c',
    'libgd/gd_png.c',
    'libgd/gd_rotate.c',
    'libgd/gd_security.c',
    'libgd/gd_ss.c',
    'libgd/gd_tga.c',
    'libgd/gd_topal.c',
    'libgd/gd_transform.c',
    'libgd/gd_wbmp.c',
    'libgd/gd_webp.c',
    'libgd/gd_xbm.c',
    'libgd/gd.c',
    'libgd/gdcache.c',
    'libgd/gdfontg.c',
    'libgd/gdfontl.c',
    'libgd/gdfontmb.c',
    'libgd/gdfonts.c',
    'libgd/gdfontt.c',
    'libgd/gdft.c',
    'libgd/gdhelpers.c',
    'libgd/gdkanji.c',
    'libgd/gdtables.c',
    'libgd/gdxpm.c',
    'libgd/wbmp.c',
)

shared_module(
    'gd',
    [ext_gd_sources],
    name_prefix : '',
    c_args : [],
    include_directories : [includes],
    dependencies : [dependency('freetype2')],
)
